variable "azure_location" {}
variable "azure_resource_group_name" {}
variable "azure_resources_prefix" {}
variable "azure_storage_prefix" {}
variable "azure_address_space" {}
variable "azure_address_prefix_master" {}
variable "azure_address_prefix_infra" {}
variable "azure_address_prefix_node" {}
variable "openshift_master_internal_load_balancer" {}
variable "openshift_node_count" {}
variable "openshift_master_count" {}
variable "openshift_infra_count" {}
variable "openshift_node_vm_size" {}
variable "openshift_master_vm_size" {}
variable "openshift_infra_vm_size" {}
variable "openshift_bastion_vm_size" {}
variable "openshift_os_image_publisher" {}
variable "openshift_os_image_offer" {}
variable "openshift_os_image_sku" {}
variable "openshift_os_image_version" {}
variable "openshift_vm_admin_user" {}
